module.exports = [
    {
        productType: "Car",
        cost: "5000",
        productName: "Rav 4",
        sold: true,
        soldBy: "Abel",
        price: "7500",
        location: "New York",
    },
    {
        productType: "Car",
        cost: "7000",
        productName: "F150",
        sold: true,
        soldBy: "Dagim",
        price: "9500",
        location: "Addis Ababa",
    },
    {
        productType: "laptop",
        cost: "500",
        productName: "Hp",
        sold: false,
    },
    {
        productType: "Phone",
        cost: "200",
        productName: "iphone",
        sold: true,
        soldBy: "Abel",
        price: "250",
        location: "Jimma",
    },
    {
        productType: "Phone",
        cost: "120",
        productName: "Samsung",
        sold: false,
    },
    {
        productType: "Tshirt",
        cost: "12",
        productName: "Polo",
        sold: true,
        soldBy: "Mike",
        price: "15",
        location: "Addis Ababa",
    },
    {
        productType: "laptop",
        cost: "1000",
        productName: "Mac",
        sold: true,
        soldBy: "John",
        price: "1500",
        location: "Adam",
    },
    {
        productType: "Car",
        cost: "3400",
        productName: "Hilux",
        sold: false,
    },
    {
        productType: "Shoe",
        cost: "28",
        productName: "Nike",
        sold: true,
        soldBy: "Abel",
        price: "30",
        location: "New York",
    },
    {
        productType: "Shoe",
        cost: "17",
        productName: "Puma",
        sold: true,
        soldBy: "Mike",
        price: "25",
        location: "Afar",
    },
    {
        productType: "Shoe",
        cost: "13",
        productName: "Vans",
        sold: false,
    },
    {
        productType: "TV",
        cost: "800",
        productName: "LG",
        sold: true,
        soldBy: "Yonas",
        price: "1200",
        location: "Afar",
    },
    {
        productType: "Watch",
        cost: "550",
        productName: "Rolex",
        sold: true,
        soldBy: "Yonas",
        price: "600",
        location: "London",
    },
    {
        productType: "Watch",
        cost: "1200",
        productName: "Rolex",
        sold: false,
    },
    {
        productType: "Bag",
        cost: "27",
        productName: "Adidas",
        sold: false,
    },
    {
        productType: "Dress",
        cost: "100",
        productName: "Pink",
        sold: false,
    },
    {
        productType: "Dress",
        cost: "60",
        productName: "Pink",
        sold: true,
        soldBy: "Tina",
        price: "90",
        location: "New York",
    },
    {
        productType: "Motor Cycle",
        cost: "618",
        productName: "Mountain",
        sold: true,
        soldBy: "Abel",
        price: "700",
        location: "Cairo",
    },
    {
        productType: "Motor Cycle",
        cost: "618",
        productName: "Mountain",
        sold: false,
    },
    {
        productType: "Sofa",
        cost: "150",
        productName: "Solina",
        sold: true,
        soldBy: "Robel",
        price: "300",
        location: "London",
    },
    {
        productType: "Bed",
        cost: "75",
        productName: "Solina",
        sold: true,
        soldBy: "Robel",
        price: "100",
        location: "London",
    },

]